name: Fuzzing

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  runscript:
    name: Build and run container
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: build
        run: |
                 chmod +x ${GITHUB_WORKSPACE}/build.sh
                 ${GITHUB_WORKSPACE}/build.sh
        shell: bash
      - name: run container
        run: |
                  chmod +x ${GITHUB_WORKSPACE}/run.sh
                  ${GITHUB_WORKSPACE}/run.sh
