name: build and run fuzzer

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  buildandrun:
    name: Build and run docker 
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Build the Docker image
      run: docker build . --tag fuzzer
    - name: Run container
      run: docker run fuzzer
